# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Look here for settings:
# https://github.com/jekyll/minima/blob/master/_config.yml
title: Carl Gieringer's Github Blog
author:
  name: Carl Gieringer
description: >- # this means to ignore newlines until "baseurl:"
  I work as a software engineer and practice insight meditation.
show_excerpts: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carlgieringer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
  
minima:
  # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%Y-%m-%d"
  social_links:
    twitter: carlgieringer
    github:  carlgieringer
    linkedin: carlgieringer

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
